name = "THTS"
uuid = "6a918302-f22c-4708-a42c-c3d98e732581"
authors = ["sarulinkaa82"]
version = "1.0.0-DEV"

[deps]
FiniteHorizonPOMDPs = "8a13bbfe-798e-11e9-2f1c-eba9ee5ef093"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
POMDPLinter = "f3bd98c0-eb40-45e2-9eb1-f2763262d755"
POMDPTools = "7588e00f-9cae-40de-98dc-e0c70c48cdd7"
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
FiniteHorizonPOMDPs = "0.4.1"
Logging = "1.11.0"
POMDPLinter = "0.1.2"
POMDPTools = "1.1.0"
POMDPs = "1.0.0"
StatsBase = "0.34.3"
julia = "1.9"
